### ISSUE TITLE
slimmable argument

### ISSUE THREAD

**Issue by shira-g** [clovaai/length-adaptive-transformer#1]
hello,

I tried to reproduce your results according to the commands suggested in the README file, and so far I couldn't do so.
I notice you refer to the 'slimmable' arg but it's not being set/initialized anywhere in the code, is that a mistake? since I notice sample length configuration will only be used during training with the 'slimmable' flag, and without it only a 'standard' training will be executed.

I will appreciate any help,
thank you.

**Comment by gyuwankim** [comment]
Hi, Shira.

Sorry for the inconvenience. The "slimmable" argument is the previous name of the "length_adaptive" argument.
It was my mistake. I just fixed it. Please check whether it works now.

Thank you.

**Comment by shira-g** [comment]
yes it works now, thank you!
